### ISSUE TITLE
Initial roadmap

### ISSUE THREAD

**Issue by fernandoabolafio** [fernandoabolafio/github-work-stats#1]
## Initial roadmap
- [x] Pull data from github by username 
- [x] Filter activity by Organization
- [x] Filter activity by a Date Range
- [x] Filter activity by Repo
- [x] Export filtered activities with details to CSV (url, date, etc)
